baseURL = "https://xtopheblog.netlify.app/"
title = "My Nihon Site"
theme = "aether"
paginate = 3
# themesDir = "../../" 

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
	brand = "Xtophe's Blog"
	description = "The website's description"
